//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloBoSach {
    
    
    public partial class _default {
        
        /// <summary>
        /// ProductListControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.ProductListControl ProductListControl;
        
        /// <summary>
        /// TitleBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.TitleBar TitleBar;
        
        /// <summary>
        /// ShowTopNewsImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.ShowTopNewsImage ShowTopNewsImage;
        
        /// <summary>
        /// TitleBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.TitleBar TitleBar1;
        
        /// <summary>
        /// ShowTopNewsImage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.ShowTopNewsImage ShowTopNewsImage1;
        
        /// <summary>
        /// TitleBar2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.TitleBar TitleBar2;
        
        /// <summary>
        /// QuangCaoNgang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.QuangCaoNgang QuangCaoNgang;
    }
}
