//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloBoSach {
    
    
    public partial class NewsList {
        
        /// <summary>
        /// divHomeNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divHomeNews;
        
        /// <summary>
        /// ShowTopNewsImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.ShowTopNewsImage ShowTopNewsImage;
        
        /// <summary>
        /// TitleBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.TitleBar TitleBar;
        
        /// <summary>
        /// ShowTopNewsImage1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.ShowTopNewsImage ShowTopNewsImage1;
        
        /// <summary>
        /// TitleBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.TitleBar TitleBar1;
        
        /// <summary>
        /// ShowTopNewsImage2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ctrl.ShowTopNewsImage ShowTopNewsImage2;
        
        /// <summary>
        /// divListNewsInLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divListNewsInLine;
        
        /// <summary>
        /// ListNewsLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HaloBoSach.ListNewsLine ListNewsLine;
    }
}
